##begin config
basename Bonami
libbase BonamiBase
libbasetype struct BonamiPrivate
version 40.1
##end config

##begin cdef
#include <utility/tagitem.h>
#include <utility/hooks.h>
#include <bonami/mdns.h>
#include <bonami/nipc.h>
##end cdef

##begin cdefprivate
#include "private/bonami_internal.h"
##end cdefprivate

##begin functionlist
LONG OpenMDNSEngine() ()
void CloseMDNSEngine() ()
LONG RegisterServiceA(struct TagItem *tags) (A0)
LONG UpdateServiceA(MDNSRegisterRef ref, struct TagItem *tags) (A0,A1)
void DeregisterService(MDNSRegisterRef ref) (A0)
LONG BrowseServiceTypeA(STRPTR type, struct Hook *hook, struct TagItem *tags) (A0,A1,A2)
void StopBrowse(MDNSBrowseRef ref) (A0)
LONG ResolveServiceA(STRPTR name, STRPTR type, struct Hook *hook, struct TagItem *tags) (A0,A1,A2,A3)
void StopResolve(MDNSResolveRef ref) (A0)
LONG MakeTXTRecordA(struct TagItem *tags, APTR *record, ULONG *recordLen) (A0,A1,A2)
void FreeTXTRecord(APTR record) (A0)
LONG GetMDNSStatusA(struct TagItem *tags) (A0)
LONG InquiryFromNIPCTagsA(struct Hook *hook, ULONG maxTime, ULONG maxResponses, struct TagItem *tags) (A0,D0,D1,A1)
LONG PublishNIPCEntitiesA(struct TagItem *tags) (A0)
void UnpublishNIPCEntitiesA() ()
##end functionlist
